-- Auto-generated ERP Seed Data SQL Dump
USE erp_db;
SET FOREIGN_KEY_CHECKS = 0;

-- Table: users
INSERT INTO `users` (`id`, `username`, `email`, `full_name`, `hashed_password`, `role`, `is_active`) VALUES (1, 'admin', 'admin@erp.com', 'System Administrator', '$2b$12$eWzX...hashpassword', 'admin', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `full_name` = VALUES(`full_name`), `hashed_password` = VALUES(`hashed_password`), `role` = VALUES(`role`), `is_active` = VALUES(`is_active`);
INSERT INTO `users` (`id`, `username`, `email`, `full_name`, `hashed_password`, `role`, `is_active`) VALUES (2, 'project_mgr', 'manager@erp.com', 'John Doe (Project Manager)', '$2b$12$eWzX...hashpassword', 'project_manager', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `full_name` = VALUES(`full_name`), `hashed_password` = VALUES(`hashed_password`), `role` = VALUES(`role`), `is_active` = VALUES(`is_active`);
INSERT INTO `users` (`id`, `username`, `email`, `full_name`, `hashed_password`, `role`, `is_active`) VALUES (3, 'site_eng', 'engineer@erp.com', 'Jane Smith (Site Engineer)', '$2b$12$eWzX...hashpassword', 'site_engineer', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `full_name` = VALUES(`full_name`), `hashed_password` = VALUES(`hashed_password`), `role` = VALUES(`role`), `is_active` = VALUES(`is_active`);

-- Table: audit_logs
INSERT INTO `audit_logs` (`id`, `user_id`, `action`, `entity_type`, `entity_id`, `payload`, `ip_address`) VALUES (1, 1, 'INITIALIZE', 'System', 1, '{"message": "Database initialized"}', '127.0.0.1') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `user_id` = VALUES(`user_id`), `action` = VALUES(`action`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`), `payload` = VALUES(`payload`), `ip_address` = VALUES(`ip_address`);
INSERT INTO `audit_logs` (`id`, `user_id`, `action`, `entity_type`, `entity_id`, `payload`, `ip_address`) VALUES (2, 2, 'CREATE_PROJECT', 'Project', 1, '{"project_name": "Skyline Towers"}', '192.168.1.5') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `user_id` = VALUES(`user_id`), `action` = VALUES(`action`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`), `payload` = VALUES(`payload`), `ip_address` = VALUES(`ip_address`);

-- Table: notifications
INSERT INTO `notifications` (`id`, `user_id`, `title`, `message`, `notification_type`, `is_read`, `entity_type`, `entity_id`) VALUES (1, 1, 'Welcome to ERP', 'System setup completed successfully.', 'info', 0, 'System', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `user_id` = VALUES(`user_id`), `title` = VALUES(`title`), `message` = VALUES(`message`), `notification_type` = VALUES(`notification_type`), `is_read` = VALUES(`is_read`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`);
INSERT INTO `notifications` (`id`, `user_id`, `title`, `message`, `notification_type`, `is_read`, `entity_type`, `entity_id`) VALUES (2, 2, 'Project Assigned', 'You have been assigned as Project Manager for Skyline Towers.', 'success', 0, 'Project', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `user_id` = VALUES(`user_id`), `title` = VALUES(`title`), `message` = VALUES(`message`), `notification_type` = VALUES(`notification_type`), `is_read` = VALUES(`is_read`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`);

-- Table: documents
INSERT INTO `documents` (`id`, `entity_type`, `entity_id`, `file_name`, `file_path`, `file_size`, `file_type`, `uploaded_by_id`) VALUES (1, 'Project', 1, 'skyline_architectural_plan.pdf', '/uploads/projects/skyline_architectural_plan.pdf', 2048500, 'application/pdf', 2) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`), `file_name` = VALUES(`file_name`), `file_path` = VALUES(`file_path`), `file_size` = VALUES(`file_size`), `file_type` = VALUES(`file_type`), `uploaded_by_id` = VALUES(`uploaded_by_id`);

-- Table: approval_tasks
INSERT INTO `approval_tasks` (`id`, `title`, `entity_type`, `entity_id`, `requester_id`, `current_stage`, `status`) VALUES (1, 'PO Approval - Structural Steel', 'PurchaseOrder', 1, 3, 'Manager Approval', 'pending') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `title` = VALUES(`title`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`), `requester_id` = VALUES(`requester_id`), `current_stage` = VALUES(`current_stage`), `status` = VALUES(`status`);

-- Table: approval_logs
INSERT INTO `approval_logs` (`id`, `approval_task_id`, `approver_id`, `stage`, `action`, `comments`) VALUES (1, 1, 2, 'Initial Review', 'forwarded', 'Verified technical specifications and quantities.') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `approval_task_id` = VALUES(`approval_task_id`), `approver_id` = VALUES(`approver_id`), `stage` = VALUES(`stage`), `action` = VALUES(`action`), `comments` = VALUES(`comments`);

-- Table: customers
INSERT INTO `customers` (`id`, `customer_code`, `name`, `contact_person`, `email`, `phone`, `company`, `customer_type`, `status`, `source_lead_id`, `address`, `city`, `state`, `postal_code`, `notes`) VALUES (1, 'CUST-001', 'Acme Corporation', 'Alice Johnson', 'alice@acme.com', '+1234567890', 'Acme Corp', 'Corporate', 'Active', NULL, '100 Business Park Suite 400', 'Metropolis', 'NY', '10001', 'Key commercial tenant') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `customer_code` = VALUES(`customer_code`), `name` = VALUES(`name`), `contact_person` = VALUES(`contact_person`), `email` = VALUES(`email`), `phone` = VALUES(`phone`), `company` = VALUES(`company`), `customer_type` = VALUES(`customer_type`), `status` = VALUES(`status`), `source_lead_id` = VALUES(`source_lead_id`), `address` = VALUES(`address`), `city` = VALUES(`city`), `state` = VALUES(`state`), `postal_code` = VALUES(`postal_code`), `notes` = VALUES(`notes`);
INSERT INTO `customers` (`id`, `customer_code`, `name`, `contact_person`, `email`, `phone`, `company`, `customer_type`, `status`, `source_lead_id`, `address`, `city`, `state`, `postal_code`, `notes`) VALUES (2, 'CUST-002', 'Robert Davis', 'Robert Davis', 'robert.davis@example.com', '+1987654321', 'Individual', 'Individual', 'Active', NULL, '45 Park Avenue', 'Metropolis', 'NY', '10002', 'Residential Buyer') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `customer_code` = VALUES(`customer_code`), `name` = VALUES(`name`), `contact_person` = VALUES(`contact_person`), `email` = VALUES(`email`), `phone` = VALUES(`phone`), `company` = VALUES(`company`), `customer_type` = VALUES(`customer_type`), `status` = VALUES(`status`), `source_lead_id` = VALUES(`source_lead_id`), `address` = VALUES(`address`), `city` = VALUES(`city`), `state` = VALUES(`state`), `postal_code` = VALUES(`postal_code`), `notes` = VALUES(`notes`);

-- Table: projects
INSERT INTO `projects` (`id`, `name`, `code`, `client_id`, `manager_id`, `location`, `start_date`, `end_date`, `budget`, `actual_cost`, `status`, `progress_pct`) VALUES (1, 'Skyline Towers', 'PROJ-001', 1, 2, 'Downtown Financial District', '2026-01-01 00:00:00', '2027-12-31 00:00:00', 5000000, 1200000, 'active', 24.5) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `code` = VALUES(`code`), `client_id` = VALUES(`client_id`), `manager_id` = VALUES(`manager_id`), `location` = VALUES(`location`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `budget` = VALUES(`budget`), `actual_cost` = VALUES(`actual_cost`), `status` = VALUES(`status`), `progress_pct` = VALUES(`progress_pct`);
INSERT INTO `projects` (`id`, `name`, `code`, `client_id`, `manager_id`, `location`, `start_date`, `end_date`, `budget`, `actual_cost`, `status`, `progress_pct`) VALUES (2, 'Green Valley Residency', 'PROJ-002', 2, 2, 'Suburban Sector 4', '2026-03-15 00:00:00', '2028-06-30 00:00:00', 8000000, 500000, 'active', 10) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `code` = VALUES(`code`), `client_id` = VALUES(`client_id`), `manager_id` = VALUES(`manager_id`), `location` = VALUES(`location`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `budget` = VALUES(`budget`), `actual_cost` = VALUES(`actual_cost`), `status` = VALUES(`status`), `progress_pct` = VALUES(`progress_pct`);

-- Table: properties
INSERT INTO `properties` (`id`, `project_id`, `name`, `code`, `property_type`, `location`, `status`, `address`, `city`, `state`, `pincode`, `description`, `total_buildings`, `total_units`) VALUES (1, 1, 'Skyline Commercial Center', 'PROP-001', 'Commercial', 'Downtown Financial District', 'Active', '100 Main Street', 'Metropolis', 'NY', '10001', 'Modern Commercial Hub', 2, 50) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `name` = VALUES(`name`), `code` = VALUES(`code`), `property_type` = VALUES(`property_type`), `location` = VALUES(`location`), `status` = VALUES(`status`), `address` = VALUES(`address`), `city` = VALUES(`city`), `state` = VALUES(`state`), `pincode` = VALUES(`pincode`), `description` = VALUES(`description`), `total_buildings` = VALUES(`total_buildings`), `total_units` = VALUES(`total_units`);

-- Table: buildings
INSERT INTO `buildings` (`id`, `property_id`, `name`, `code`, `building_type`, `total_floors`, `total_units`, `status`, `address`, `description`, `completion_date`) VALUES (1, 1, 'Tower A', 'BLD-A', 'Tower', 15, 25, 'Active', '100 Main Street - Tower A', 'North Commercial Tower', '2027-06-30 00:00:00') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `property_id` = VALUES(`property_id`), `name` = VALUES(`name`), `code` = VALUES(`code`), `building_type` = VALUES(`building_type`), `total_floors` = VALUES(`total_floors`), `total_units` = VALUES(`total_units`), `status` = VALUES(`status`), `address` = VALUES(`address`), `description` = VALUES(`description`), `completion_date` = VALUES(`completion_date`);

-- Table: property_units
INSERT INTO `property_units` (`id`, `building_id`, `unit_number`, `unit_code`, `unit_type`, `floor_number`, `area_sqft`, `carpet_area`, `builtup_area`, `facing`, `configuration`, `rate_per_sqft`, `total_price`, `status`, `description`) VALUES (1, 1, '101', 'UNIT-101', 'Office Space', 1, 1200, 1000, 1200, 'East', 'Open Layout', 150, 180000, 'AVAILABLE', 'Corner Office with City View') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `building_id` = VALUES(`building_id`), `unit_number` = VALUES(`unit_number`), `unit_code` = VALUES(`unit_code`), `unit_type` = VALUES(`unit_type`), `floor_number` = VALUES(`floor_number`), `area_sqft` = VALUES(`area_sqft`), `carpet_area` = VALUES(`carpet_area`), `builtup_area` = VALUES(`builtup_area`), `facing` = VALUES(`facing`), `configuration` = VALUES(`configuration`), `rate_per_sqft` = VALUES(`rate_per_sqft`), `total_price` = VALUES(`total_price`), `status` = VALUES(`status`), `description` = VALUES(`description`);
INSERT INTO `property_units` (`id`, `building_id`, `unit_number`, `unit_code`, `unit_type`, `floor_number`, `area_sqft`, `carpet_area`, `builtup_area`, `facing`, `configuration`, `rate_per_sqft`, `total_price`, `status`, `description`) VALUES (2, 1, '102', 'UNIT-102', 'Office Space', 1, 1500, 1300, 1500, 'North', 'Executive Suite', 160, 240000, 'BOOKED', 'Executive Office Suite') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `building_id` = VALUES(`building_id`), `unit_number` = VALUES(`unit_number`), `unit_code` = VALUES(`unit_code`), `unit_type` = VALUES(`unit_type`), `floor_number` = VALUES(`floor_number`), `area_sqft` = VALUES(`area_sqft`), `carpet_area` = VALUES(`carpet_area`), `builtup_area` = VALUES(`builtup_area`), `facing` = VALUES(`facing`), `configuration` = VALUES(`configuration`), `rate_per_sqft` = VALUES(`rate_per_sqft`), `total_price` = VALUES(`total_price`), `status` = VALUES(`status`), `description` = VALUES(`description`);

-- Table: crm_leads
INSERT INTO `crm_leads` (`id`, `customer_name`, `email`, `phone`, `company`, `property_category`, `interested_unit_id`, `project_id`, `property_id`, `preferred_unit_type`, `budget`, `source`, `salesperson_id`, `stage`, `lead_type`, `priority`, `requirement`, `notes`, `qualification_notes`, `expected_closing_date`, `requirement_confirmed`, `budget_available`, `decision_maker_identified`) VALUES (1, 'Charlie Brown', 'charlie@leads.com', '+1122334455', 'Brown Enterprise', 'Commercial', 1, 1, 1, 'Office Space', 200000, 'Website', 2, 'QUALIFIED', 'Individual', 'High', 'Requires 1200 sqft office space', 'Schedule site visit next week', 'Budget confirmed', '2026-10-15 00:00:00', 1, 1, 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `customer_name` = VALUES(`customer_name`), `email` = VALUES(`email`), `phone` = VALUES(`phone`), `company` = VALUES(`company`), `property_category` = VALUES(`property_category`), `interested_unit_id` = VALUES(`interested_unit_id`), `project_id` = VALUES(`project_id`), `property_id` = VALUES(`property_id`), `preferred_unit_type` = VALUES(`preferred_unit_type`), `budget` = VALUES(`budget`), `source` = VALUES(`source`), `salesperson_id` = VALUES(`salesperson_id`), `stage` = VALUES(`stage`), `lead_type` = VALUES(`lead_type`), `priority` = VALUES(`priority`), `requirement` = VALUES(`requirement`), `notes` = VALUES(`notes`), `qualification_notes` = VALUES(`qualification_notes`), `expected_closing_date` = VALUES(`expected_closing_date`), `requirement_confirmed` = VALUES(`requirement_confirmed`), `budget_available` = VALUES(`budget_available`), `decision_maker_identified` = VALUES(`decision_maker_identified`);

-- Table: crm_followups
INSERT INTO `crm_followups` (`id`, `lead_id`, `followup_date`, `followup_type`, `notes`, `next_action`, `status`) VALUES (1, 1, '2026-09-15 10:00:00', 'Call', 'Discussed unit pricing and discount options.', 'Send formal proposal package', 'Scheduled') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `lead_id` = VALUES(`lead_id`), `followup_date` = VALUES(`followup_date`), `followup_type` = VALUES(`followup_type`), `notes` = VALUES(`notes`), `next_action` = VALUES(`next_action`), `status` = VALUES(`status`);

-- Table: crm_site_visits
INSERT INTO `crm_site_visits` (`id`, `lead_id`, `property_id`, `visit_date`, `assigned_executive_id`, `status`, `notes`, `customer_feedback`, `interest_level`, `next_action`) VALUES (1, 1, 1, '2026-09-12 14:00:00', 2, 'Completed', 'Toured Unit 101 and 102.', 'Impression was highly positive.', 'High', 'Prepare agreement draft') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `lead_id` = VALUES(`lead_id`), `property_id` = VALUES(`property_id`), `visit_date` = VALUES(`visit_date`), `assigned_executive_id` = VALUES(`assigned_executive_id`), `status` = VALUES(`status`), `notes` = VALUES(`notes`), `customer_feedback` = VALUES(`customer_feedback`), `interest_level` = VALUES(`interest_level`), `next_action` = VALUES(`next_action`);

-- Table: crm_lead_activities
INSERT INTO `crm_lead_activities` (`id`, `lead_id`, `activity_type`, `description`) VALUES (1, 1, 'EMAIL_SENT', 'Emailed brochure and floor plan to customer.') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `lead_id` = VALUES(`lead_id`), `activity_type` = VALUES(`activity_type`), `description` = VALUES(`description`);

-- Table: property_bookings
INSERT INTO `property_bookings` (`id`, `booking_number`, `unit_id`, `customer_id`, `salesperson_id`, `booking_amount`, `discount`, `total_price`, `agreement_status`, `allotment_date`, `expected_agreement_date`, `status`, `remarks`, `notes`) VALUES (1, 'BK-2026-001', 2, 1, 2, 20000, 5000, 235000, 'Draft', '2026-09-01 00:00:00', '2026-09-20 00:00:00', 'CONFIRMED', 'Booking deposit confirmed via wire transfer.', 'Client requested customized interior partition.') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `booking_number` = VALUES(`booking_number`), `unit_id` = VALUES(`unit_id`), `customer_id` = VALUES(`customer_id`), `salesperson_id` = VALUES(`salesperson_id`), `booking_amount` = VALUES(`booking_amount`), `discount` = VALUES(`discount`), `total_price` = VALUES(`total_price`), `agreement_status` = VALUES(`agreement_status`), `allotment_date` = VALUES(`allotment_date`), `expected_agreement_date` = VALUES(`expected_agreement_date`), `status` = VALUES(`status`), `remarks` = VALUES(`remarks`), `notes` = VALUES(`notes`);

-- Table: payment_installments
INSERT INTO `payment_installments` (`id`, `booking_id`, `customer_id`, `installment_name`, `sequence_number`, `due_date`, `amount`, `paid_amount`, `balance_amount`, `status`, `paid_date`, `payment_reference`) VALUES (1, 1, 1, 'Booking Token', 1, '2026-09-01 00:00:00', 20000, 20000, 0, 'PAID', '2026-09-01 00:00:00', 'TXN-TOKEN-001') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `booking_id` = VALUES(`booking_id`), `customer_id` = VALUES(`customer_id`), `installment_name` = VALUES(`installment_name`), `sequence_number` = VALUES(`sequence_number`), `due_date` = VALUES(`due_date`), `amount` = VALUES(`amount`), `paid_amount` = VALUES(`paid_amount`), `balance_amount` = VALUES(`balance_amount`), `status` = VALUES(`status`), `paid_date` = VALUES(`paid_date`), `payment_reference` = VALUES(`payment_reference`);
INSERT INTO `payment_installments` (`id`, `booking_id`, `customer_id`, `installment_name`, `sequence_number`, `due_date`, `amount`, `paid_amount`, `balance_amount`, `status`, `paid_date`, `payment_reference`) VALUES (2, 1, 1, 'Installment 1 (10%)', 2, '2026-10-01 00:00:00', 23500, 0, 23500, 'PENDING', NULL, NULL) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `booking_id` = VALUES(`booking_id`), `customer_id` = VALUES(`customer_id`), `installment_name` = VALUES(`installment_name`), `sequence_number` = VALUES(`sequence_number`), `due_date` = VALUES(`due_date`), `amount` = VALUES(`amount`), `paid_amount` = VALUES(`paid_amount`), `balance_amount` = VALUES(`balance_amount`), `status` = VALUES(`status`), `paid_date` = VALUES(`paid_date`), `payment_reference` = VALUES(`payment_reference`);

-- Table: property_payments
INSERT INTO `property_payments` (`id`, `payment_code`, `installment_id`, `booking_id`, `customer_id`, `amount`, `payment_date`, `payment_method`, `reference_number`, `remarks`, `created_by_id`) VALUES (1, 'PAY-2026-001', 1, 1, 1, 20000, '2026-09-01 11:30:00', 'Bank Transfer', 'TXN-TOKEN-001', 'Received via NEFT from Acme Corp', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `payment_code` = VALUES(`payment_code`), `installment_id` = VALUES(`installment_id`), `booking_id` = VALUES(`booking_id`), `customer_id` = VALUES(`customer_id`), `amount` = VALUES(`amount`), `payment_date` = VALUES(`payment_date`), `payment_method` = VALUES(`payment_method`), `reference_number` = VALUES(`reference_number`), `remarks` = VALUES(`remarks`), `created_by_id` = VALUES(`created_by_id`);

-- Table: wbs_tasks
INSERT INTO `wbs_tasks` (`id`, `project_id`, `parent_task_id`, `title`, `task_level`, `predecessor_id`, `contractor_name`, `start_date`, `end_date`, `planned_qty`, `actual_qty`, `planned_budget`, `actual_cost`, `progress_pct`, `status`) VALUES (1, 1, NULL, 'Foundation & Substructure', 'Phase', NULL, 'BuildCorp Infrastructure', '2026-01-05 00:00:00', '2026-03-31 00:00:00', 100, 100, 500000, 480000, 100, 'completed') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `parent_task_id` = VALUES(`parent_task_id`), `title` = VALUES(`title`), `task_level` = VALUES(`task_level`), `predecessor_id` = VALUES(`predecessor_id`), `contractor_name` = VALUES(`contractor_name`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `planned_qty` = VALUES(`planned_qty`), `actual_qty` = VALUES(`actual_qty`), `planned_budget` = VALUES(`planned_budget`), `actual_cost` = VALUES(`actual_cost`), `progress_pct` = VALUES(`progress_pct`), `status` = VALUES(`status`);
INSERT INTO `wbs_tasks` (`id`, `project_id`, `parent_task_id`, `title`, `task_level`, `predecessor_id`, `contractor_name`, `start_date`, `end_date`, `planned_qty`, `actual_qty`, `planned_budget`, `actual_cost`, `progress_pct`, `status`) VALUES (2, 1, 1, 'Superstructure Framing - Floor 1-5', 'Task', 1, 'BuildCorp Infrastructure', '2026-04-01 00:00:00', '2026-08-31 00:00:00', 100, 60, 1200000, 720000, 60, 'in_progress') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `parent_task_id` = VALUES(`parent_task_id`), `title` = VALUES(`title`), `task_level` = VALUES(`task_level`), `predecessor_id` = VALUES(`predecessor_id`), `contractor_name` = VALUES(`contractor_name`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `planned_qty` = VALUES(`planned_qty`), `actual_qty` = VALUES(`actual_qty`), `planned_budget` = VALUES(`planned_budget`), `actual_cost` = VALUES(`actual_cost`), `progress_pct` = VALUES(`progress_pct`), `status` = VALUES(`status`);

-- Table: site_daily_logs
INSERT INTO `site_daily_logs` (`id`, `project_id`, `engineer_id`, `log_date`, `physical_progress`, `labour_count`, `materials_consumed`, `equipment_used`, `issues_identified`, `remarks`, `approval_status`) VALUES (1, 1, 3, '2026-09-08 17:00:00', 'Poured RCC columns for 3rd floor Block A', 35, 'Cement 250 bags, Steel 6.2 Tons', 'Concrete Pump, Tower Crane', 'None reported', 'Weather clear, target achieved.', 'approved') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `engineer_id` = VALUES(`engineer_id`), `log_date` = VALUES(`log_date`), `physical_progress` = VALUES(`physical_progress`), `labour_count` = VALUES(`labour_count`), `materials_consumed` = VALUES(`materials_consumed`), `equipment_used` = VALUES(`equipment_used`), `issues_identified` = VALUES(`issues_identified`), `remarks` = VALUES(`remarks`), `approval_status` = VALUES(`approval_status`);

-- Table: vendors
INSERT INTO `vendors` (`id`, `name`, `code`, `contact_person`, `email`, `phone`, `gst_number`, `pan_number`, `rating`, `status`) VALUES (1, 'Apex Building Materials Ltd', 'VEN-001', 'David Miller', 'sales@apexmaterials.com', '+1555666777', '29ABCDE1234F1Z5', 'ABCDE1234F', 4.8, 'active') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `code` = VALUES(`code`), `contact_person` = VALUES(`contact_person`), `email` = VALUES(`email`), `phone` = VALUES(`phone`), `gst_number` = VALUES(`gst_number`), `pan_number` = VALUES(`pan_number`), `rating` = VALUES(`rating`), `status` = VALUES(`status`);
INSERT INTO `vendors` (`id`, `name`, `code`, `contact_person`, `email`, `phone`, `gst_number`, `pan_number`, `rating`, `status`) VALUES (2, 'BuildCorp Infrastructure', 'VEN-002', 'Sarah Connor', 'contact@buildcorp.com', '+1555888999', '27XYZAB5678G2Z1', 'XYZAB5678G', 4.6, 'active') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `code` = VALUES(`code`), `contact_person` = VALUES(`contact_person`), `email` = VALUES(`email`), `phone` = VALUES(`phone`), `gst_number` = VALUES(`gst_number`), `pan_number` = VALUES(`pan_number`), `rating` = VALUES(`rating`), `status` = VALUES(`status`);

-- Table: purchase_requisitions
INSERT INTO `purchase_requisitions` (`id`, `req_number`, `project_id`, `requester_id`, `title`, `estimated_cost`, `status`) VALUES (1, 'PR-2026-001', 1, 3, 'Procurement of TMT Steel Bars (Grade Fe500)', 150000, 'approved') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `req_number` = VALUES(`req_number`), `project_id` = VALUES(`project_id`), `requester_id` = VALUES(`requester_id`), `title` = VALUES(`title`), `estimated_cost` = VALUES(`estimated_cost`), `status` = VALUES(`status`);

-- Table: purchase_orders
INSERT INTO `purchase_orders` (`id`, `po_number`, `pr_id`, `project_id`, `vendor_id`, `total_amount`, `status`) VALUES (1, 'PO-2026-001', 1, 1, 1, 145000, 'approved') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `po_number` = VALUES(`po_number`), `pr_id` = VALUES(`pr_id`), `project_id` = VALUES(`project_id`), `vendor_id` = VALUES(`vendor_id`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);

-- Table: boq_items
INSERT INTO `boq_items` (`id`, `project_id`, `item_name`, `unit`, `approved_qty`, `rate`, `total_amount`, `contractor_name`) VALUES (1, 1, 'Reinforced Concrete M30 Grade', 'Cum', 500, 4500, 2250000, 'BuildCorp Infrastructure') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `item_name` = VALUES(`item_name`), `unit` = VALUES(`unit`), `approved_qty` = VALUES(`approved_qty`), `rate` = VALUES(`rate`), `total_amount` = VALUES(`total_amount`), `contractor_name` = VALUES(`contractor_name`);
INSERT INTO `boq_items` (`id`, `project_id`, `item_name`, `unit`, `approved_qty`, `rate`, `total_amount`, `contractor_name`) VALUES (2, 1, 'Structural Steel Fe500', 'MT', 50, 65000, 3250000, 'Apex Building Materials Ltd') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `item_name` = VALUES(`item_name`), `unit` = VALUES(`unit`), `approved_qty` = VALUES(`approved_qty`), `rate` = VALUES(`rate`), `total_amount` = VALUES(`total_amount`), `contractor_name` = VALUES(`contractor_name`);

-- Table: measurement_books
INSERT INTO `measurement_books` (`id`, `project_id`, `boq_item_id`, `engineer_id`, `log_date`, `location_zone`, `measured_qty`, `remarks`) VALUES (1, 1, 1, 3, '2026-09-05 00:00:00', 'Zone A Floor 3 Column C1-C12', 45, 'Inspected and certified by lead engineer.') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `project_id` = VALUES(`project_id`), `boq_item_id` = VALUES(`boq_item_id`), `engineer_id` = VALUES(`engineer_id`), `log_date` = VALUES(`log_date`), `location_zone` = VALUES(`location_zone`), `measured_qty` = VALUES(`measured_qty`), `remarks` = VALUES(`remarks`);

-- Table: contractor_bills
INSERT INTO `contractor_bills` (`id`, `bill_number`, `project_id`, `vendor_id`, `boq_item_id`, `billed_qty`, `billed_rate`, `total_billed_amount`, `mb_qty`, `boq_qty`, `discrepancy_flag`, `discrepancy_reason`, `status`) VALUES (1, 'BILL-2026-001', 1, 2, 1, 45, 4500, 202500, 45, 500, 0, NULL, 'verified') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `bill_number` = VALUES(`bill_number`), `project_id` = VALUES(`project_id`), `vendor_id` = VALUES(`vendor_id`), `boq_item_id` = VALUES(`boq_item_id`), `billed_qty` = VALUES(`billed_qty`), `billed_rate` = VALUES(`billed_rate`), `total_billed_amount` = VALUES(`total_billed_amount`), `mb_qty` = VALUES(`mb_qty`), `boq_qty` = VALUES(`boq_qty`), `discrepancy_flag` = VALUES(`discrepancy_flag`), `discrepancy_reason` = VALUES(`discrepancy_reason`), `status` = VALUES(`status`);

-- Table: hse_incidents
INSERT INTO `hse_incidents` (`id`, `incident_code`, `project_id`, `reporter_id`, `incident_date`, `incident_type`, `severity`, `title`, `location`, `description`, `immediate_action`, `root_cause`, `status`) VALUES (1, 'HSE-2026-001', 1, 3, '2026-09-02 11:15:00', 'Near Miss', 'medium', 'Loose Scaffolding Clamp on 3rd Floor', 'Tower A - Floor 3', 'Scaffolding clamp was found loose during morning audit.', 'Work paused, clamp tightened immediately.', 'Vibration from heavy concrete pouring nearby.', 'closed') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `incident_code` = VALUES(`incident_code`), `project_id` = VALUES(`project_id`), `reporter_id` = VALUES(`reporter_id`), `incident_date` = VALUES(`incident_date`), `incident_type` = VALUES(`incident_type`), `severity` = VALUES(`severity`), `title` = VALUES(`title`), `location` = VALUES(`location`), `description` = VALUES(`description`), `immediate_action` = VALUES(`immediate_action`), `root_cause` = VALUES(`root_cause`), `status` = VALUES(`status`);

-- Table: hse_capas
INSERT INTO `hse_capas` (`id`, `capa_code`, `project_id`, `incident_id`, `problem_description`, `root_cause`, `corrective_action`, `preventive_action`, `target_date`, `responsible_user_id`, `status`) VALUES (1, 'CAPA-2026-001', 1, 1, 'Scaffolding clamp loose on 3rd Floor', 'Vibration slackening standard clamp bolts', 'Tighten all clamps on Floor 3', 'Introduce daily pre-shift scaffolding inspection', '2026-09-10 00:00:00', 3, 'completed') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `capa_code` = VALUES(`capa_code`), `project_id` = VALUES(`project_id`), `incident_id` = VALUES(`incident_id`), `problem_description` = VALUES(`problem_description`), `root_cause` = VALUES(`root_cause`), `corrective_action` = VALUES(`corrective_action`), `preventive_action` = VALUES(`preventive_action`), `target_date` = VALUES(`target_date`), `responsible_user_id` = VALUES(`responsible_user_id`), `status` = VALUES(`status`);

-- Table: safety_audits
INSERT INTO `safety_audits` (`id`, `audit_code`, `project_id`, `auditor_id`, `audit_date`, `checklist_type`, `compliance_score_pct`, `issues_found`, `status`) VALUES (1, 'AUD-2026-001', 1, 2, '2026-09-01 09:00:00', 'Monthly Safety Audit', 95, 'Minor PPE non-compliance rectified on spot', 'passed') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `audit_code` = VALUES(`audit_code`), `project_id` = VALUES(`project_id`), `auditor_id` = VALUES(`auditor_id`), `audit_date` = VALUES(`audit_date`), `checklist_type` = VALUES(`checklist_type`), `compliance_score_pct` = VALUES(`compliance_score_pct`), `issues_found` = VALUES(`issues_found`), `status` = VALUES(`status`);

-- Table: quality_inspections
INSERT INTO `quality_inspections` (`id`, `inspection_code`, `project_id`, `task_id`, `inspector_id`, `inspection_date`, `inspection_type`, `result`, `remarks`) VALUES (1, 'INSP-2026-001', 1, 2, 3, '2026-09-04 14:30:00', 'Concrete Slump Test', 'passed', 'Concrete slump within target range 100-120mm') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `inspection_code` = VALUES(`inspection_code`), `project_id` = VALUES(`project_id`), `task_id` = VALUES(`task_id`), `inspector_id` = VALUES(`inspector_id`), `inspection_date` = VALUES(`inspection_date`), `inspection_type` = VALUES(`inspection_type`), `result` = VALUES(`result`), `remarks` = VALUES(`remarks`);

-- Table: quality_ncrs
INSERT INTO `quality_ncrs` (`id`, `ncr_code`, `project_id`, `inspection_id`, `inspector_id`, `description`, `severity`, `required_action`, `status`) VALUES (1, 'NCR-2026-001', 1, 1, 3, 'Minor honeycomb patch on column C4 base', 'minor', 'Apply non-shrink polymer mortar finish', 'closed') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `ncr_code` = VALUES(`ncr_code`), `project_id` = VALUES(`project_id`), `inspection_id` = VALUES(`inspection_id`), `inspector_id` = VALUES(`inspector_id`), `description` = VALUES(`description`), `severity` = VALUES(`severity`), `required_action` = VALUES(`required_action`), `status` = VALUES(`status`);

-- Table: tenants
INSERT INTO `tenants` (`id`, `tenant_code`, `name`, `company_name`, `email`, `phone`, `unit_id`, `rent_amount`, `lease_start`, `lease_end`, `security_deposit`, `status`) VALUES (1, 'TNT-001', 'Nexus Technologies', 'Nexus Tech Pvt Ltd', 'contact@nexustech.com', '+1999888777', 2, 3500, '2026-01-01 00:00:00', '2027-12-31 00:00:00', 10500, 'active') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `tenant_code` = VALUES(`tenant_code`), `name` = VALUES(`name`), `company_name` = VALUES(`company_name`), `email` = VALUES(`email`), `phone` = VALUES(`phone`), `unit_id` = VALUES(`unit_id`), `rent_amount` = VALUES(`rent_amount`), `lease_start` = VALUES(`lease_start`), `lease_end` = VALUES(`lease_end`), `security_deposit` = VALUES(`security_deposit`), `status` = VALUES(`status`);

-- Table: helpdesk_tickets
INSERT INTO `helpdesk_tickets` (`id`, `ticket_code`, `tenant_id`, `unit_id`, `category`, `priority`, `subject`, `description`, `assigned_technician_id`, `status`) VALUES (1, 'TKT-2026-001', 1, 2, 'HVAC', 'medium', 'AC Thermostat Error', 'Thermostat in main hall displaying error code E4', 3, 'open') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `ticket_code` = VALUES(`ticket_code`), `tenant_id` = VALUES(`tenant_id`), `unit_id` = VALUES(`unit_id`), `category` = VALUES(`category`), `priority` = VALUES(`priority`), `subject` = VALUES(`subject`), `description` = VALUES(`description`), `assigned_technician_id` = VALUES(`assigned_technician_id`), `status` = VALUES(`status`);

-- Table: facility_work_orders
INSERT INTO `facility_work_orders` (`id`, `work_order_code`, `property_id`, `unit_id`, `technician_id`, `maintenance_type`, `description`, `scheduled_date`, `estimated_cost`, `status`) VALUES (1, 'FWO-2026-001', 1, 2, 3, 'Preventive', 'Quarterly HVAC filter replacement and inspection', '2026-09-20 09:00:00', 250, 'open') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `work_order_code` = VALUES(`work_order_code`), `property_id` = VALUES(`property_id`), `unit_id` = VALUES(`unit_id`), `technician_id` = VALUES(`technician_id`), `maintenance_type` = VALUES(`maintenance_type`), `description` = VALUES(`description`), `scheduled_date` = VALUES(`scheduled_date`), `estimated_cost` = VALUES(`estimated_cost`), `status` = VALUES(`status`);

-- Table: utility_bills
INSERT INTO `utility_bills` (`id`, `bill_code`, `unit_id`, `utility_type`, `meter_number`, `prev_reading`, `curr_reading`, `units_consumed`, `rate_per_unit`, `total_amount`, `due_date`, `status`) VALUES (1, 'UTIL-2026-09-01', 2, 'Electricity', 'MTR-884920', 1450, 1820, 370, 0.15, 55.5, '2026-09-30 00:00:00', 'pending') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `bill_code` = VALUES(`bill_code`), `unit_id` = VALUES(`unit_id`), `utility_type` = VALUES(`utility_type`), `meter_number` = VALUES(`meter_number`), `prev_reading` = VALUES(`prev_reading`), `curr_reading` = VALUES(`curr_reading`), `units_consumed` = VALUES(`units_consumed`), `rate_per_unit` = VALUES(`rate_per_unit`), `total_amount` = VALUES(`total_amount`), `due_date` = VALUES(`due_date`), `status` = VALUES(`status`);

-- Table: visitor_passes
INSERT INTO `visitor_passes` (`id`, `pass_code`, `property_id`, `unit_id`, `visitor_name`, `visitor_phone`, `purpose`, `check_in_time`, `check_out_time`, `status`) VALUES (1, 'VP-2026-001', 1, 2, 'Edward Norton', '+1444555666', 'Client Executive Meeting with Nexus Tech', '2026-09-09 10:00:00', '2026-09-09 11:30:00', 'checked_out') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `pass_code` = VALUES(`pass_code`), `property_id` = VALUES(`property_id`), `unit_id` = VALUES(`unit_id`), `visitor_name` = VALUES(`visitor_name`), `visitor_phone` = VALUES(`visitor_phone`), `purpose` = VALUES(`purpose`), `check_in_time` = VALUES(`check_in_time`), `check_out_time` = VALUES(`check_out_time`), `status` = VALUES(`status`);

-- Table: tally_sync_queue
INSERT INTO `tally_sync_queue` (`id`, `sync_code`, `voucher_type`, `entity_type`, `entity_id`, `payload_xml`, `payload_json`, `status`, `retry_count`, `error_log`, `synced_at`) VALUES (1, 'TSYNC-001', 'Sales', 'PropertyBooking', 1, '<VOUCHER><TYPE>Sales</TYPE></VOUCHER>', '{"voucher_type":"Sales","booking_id":1}', 'synced', 0, NULL, '2026-09-01 12:00:00') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `sync_code` = VALUES(`sync_code`), `voucher_type` = VALUES(`voucher_type`), `entity_type` = VALUES(`entity_type`), `entity_id` = VALUES(`entity_id`), `payload_xml` = VALUES(`payload_xml`), `payload_json` = VALUES(`payload_json`), `status` = VALUES(`status`), `retry_count` = VALUES(`retry_count`), `error_log` = VALUES(`error_log`), `synced_at` = VALUES(`synced_at`);

-- Table: products
INSERT INTO `products` (`id`, `sku`, `name`, `category`, `price`, `cost`, `stock`, `min_stock_alert`) VALUES (1, 'SKU-CEMENT-01', 'Portland Cement 50kg Bag', 'Building Materials', 8.5, 6, 1000, 50) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `sku` = VALUES(`sku`), `name` = VALUES(`name`), `category` = VALUES(`category`), `price` = VALUES(`price`), `cost` = VALUES(`cost`), `stock` = VALUES(`stock`), `min_stock_alert` = VALUES(`min_stock_alert`);
INSERT INTO `products` (`id`, `sku`, `name`, `category`, `price`, `cost`, `stock`, `min_stock_alert`) VALUES (2, 'SKU-STEEL-01', 'TMT Bar 12mm (per kg)', 'Steel', 0.95, 0.7, 5000, 500) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `sku` = VALUES(`sku`), `name` = VALUES(`name`), `category` = VALUES(`category`), `price` = VALUES(`price`), `cost` = VALUES(`cost`), `stock` = VALUES(`stock`), `min_stock_alert` = VALUES(`min_stock_alert`);

-- Table: sales_orders
INSERT INTO `sales_orders` (`id`, `order_number`, `customer_id`, `total_amount`, `status`, `order_date`) VALUES (1, 'SO-2026-001', 1, 1250, 'completed', '2026-09-02 10:00:00') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `order_number` = VALUES(`order_number`), `customer_id` = VALUES(`customer_id`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`), `order_date` = VALUES(`order_date`);

-- Table: order_items
INSERT INTO `order_items` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `total_price`) VALUES (1, 1, 1, 100, 8.5, 850) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `order_id` = VALUES(`order_id`), `product_id` = VALUES(`product_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `total_price` = VALUES(`total_price`);
INSERT INTO `order_items` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `total_price`) VALUES (2, 1, 2, 400, 1, 400) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `order_id` = VALUES(`order_id`), `product_id` = VALUES(`product_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `total_price` = VALUES(`total_price`);

-- Table: site_log_photos
INSERT INTO `site_log_photos` (`id`, `site_log_id`, `project_id`, `phase_id`, `task_id`, `subtask_id`, `boq_item_id`, `file_name`, `file_path`, `file_size`, `file_type`, `caption`, `uploaded_by_id`) VALUES (1, 1, 1, NULL, 1, NULL, 1, 'foundation_pour.jpg', '/uploads/photos/foundation_pour.jpg', 1048576, 'image/jpeg', 'Concrete pouring progress on foundation', 3) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `site_log_id` = VALUES(`site_log_id`), `project_id` = VALUES(`project_id`), `phase_id` = VALUES(`phase_id`), `task_id` = VALUES(`task_id`), `subtask_id` = VALUES(`subtask_id`), `boq_item_id` = VALUES(`boq_item_id`), `file_name` = VALUES(`file_name`), `file_path` = VALUES(`file_path`), `file_size` = VALUES(`file_size`), `file_type` = VALUES(`file_type`), `caption` = VALUES(`caption`), `uploaded_by_id` = VALUES(`uploaded_by_id`);

-- Table: contractor_awards
INSERT INTO `contractor_awards` (`id`, `award_reference`, `project_id`, `estimate_id`, `contractor_id`, `estimated_amount`, `award_amount`, `variance_amount`, `variance_percentage`, `award_date`, `start_date`, `completion_date`, `status`, `remarks`) VALUES (1, 'AWD-2026-001', 1, 1, 2, 500000, 480000, -20000, -4, '2026-01-02 00:00:00', '2026-01-05 00:00:00', '2026-06-30 00:00:00', 'DRAFT', 'Contract awarded after tender process') ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `award_reference` = VALUES(`award_reference`), `project_id` = VALUES(`project_id`), `estimate_id` = VALUES(`estimate_id`), `contractor_id` = VALUES(`contractor_id`), `estimated_amount` = VALUES(`estimated_amount`), `award_amount` = VALUES(`award_amount`), `variance_amount` = VALUES(`variance_amount`), `variance_percentage` = VALUES(`variance_percentage`), `award_date` = VALUES(`award_date`), `start_date` = VALUES(`start_date`), `completion_date` = VALUES(`completion_date`), `status` = VALUES(`status`), `remarks` = VALUES(`remarks`);

-- Table: work_orders
INSERT INTO `work_orders` (`id`, `work_order_number`, `award_id`, `project_id`, `contractor_id`, `issue_date`, `scope_of_work`, `description`, `work_order_value`, `start_date`, `completion_date`, `payment_terms`, `terms_conditions`, `remarks`, `cancellation_reason`, `included_packages`, `status`, `created_by_id`) VALUES (1, 'WO-2026-001', 1, 1, 2, '2026-01-03 00:00:00', 'Civil and Structural Construction', 'Scope includes foundation, RCC frame, masonry', 480000, '2026-01-05 00:00:00', '2026-06-30 00:00:00', 'Milestone 30-60-10', 'Standard ERP T&C', 'Work order active', NULL, 'Package 1 - Civil', 'DRAFT', 1) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `work_order_number` = VALUES(`work_order_number`), `award_id` = VALUES(`award_id`), `project_id` = VALUES(`project_id`), `contractor_id` = VALUES(`contractor_id`), `issue_date` = VALUES(`issue_date`), `scope_of_work` = VALUES(`scope_of_work`), `description` = VALUES(`description`), `work_order_value` = VALUES(`work_order_value`), `start_date` = VALUES(`start_date`), `completion_date` = VALUES(`completion_date`), `payment_terms` = VALUES(`payment_terms`), `terms_conditions` = VALUES(`terms_conditions`), `remarks` = VALUES(`remarks`), `cancellation_reason` = VALUES(`cancellation_reason`), `included_packages` = VALUES(`included_packages`), `status` = VALUES(`status`), `created_by_id` = VALUES(`created_by_id`);

SET FOREIGN_KEY_CHECKS = 1;
